server:  
    port: 8201
    servlet: 
       session.timeout: 60000 
       contextpath: /bikemanage
    undertow:  
        io-threads: 16  
        worker-threads: 256  
        buffer-size: 1024  
        buffers-per-region: 1024  
        direct-buffers: true 
        
logging:
    level: 
        root: info
        org.springframework: info
        com.yc: info
    file: D://logs/yc.log
swagger: 
    enabled: true



spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ibike?serverTimezone=UTC
        username: root
        password: a
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 30000
            minimum-idle: 5
            maximum-pool-size: 20
            auto-commit: true
            idle-timeout: 600000
            pool-name: DataSourceHikariCP
            max-lifetime: 1800000
            connection-test-query: SELECT 1
    data:
        mongodb:
            # 单机
            host: localhost
            port: 27017
            # 集群
            # uri: mongodb://192.168.36.200:23000,192.168.36.201:23000,192.168.36.202:23000/yc74ibike?readPreference=secondaryPreferred
            database: yc74ibike
    redis:
        host: localhost
        port: 6379
#        cluster:
#            nodes: 192.168.36.200:6379,192.168.36.201:6379,192.168.36.202:6379,192.168.36.203:6379,192.168.36.200:6380,192.168.36.201:6380,
#            max-redirects: 3
#        jedis:
#            pool:
#                max-active: 8
#                max-idle: 8
#                max-wait: -1
#                min-idle: 0